name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    container: golang:1.23.7
    steps:
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: make
  test:
    runs-on: ubuntu-22.04
    container: golang:1.23.7
    steps:
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: make test